##spring:
##  application:
##    name: authservice
##  cloud:
##    config:
##      profile: dev
##  config:
##    import: configserver:http://localhost:8050/
#
#
#server:
#  port: 8090
#spring:
#  application:
#    name: authservice
#  datasource:
#    url: jdbc:postgresql://localhost:5434/identityDB
#    username: postgres
#    password: 1234
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#eureka:
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8888/eureka
#  instance:
#    instance-id: ${spring.application.name}:${instanceId:${random.value}}
#    preferIpAddress: true